openapi: 3.0.0
info:
  title: Movie Database API
  version: 1.0.0
servers:
  - url: https://api.themoviedb.org/3
paths:
  /search/movie:
    get:
      summary: Search for movies
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: api_key
          in: query
          required: true
          schema:
            type: string
  /movie/popular:
    get:
      summary: Get popular movies
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
